version: "3.1"
services:
  nexus:
    image: sonatype/nexus:oss 
    volumes:
      - /opt/nexus:/sonatype-work
    secrets:
      - source: dfp_admin_password
        target: dfp_admin_password
        uid: "0"
        gid: "0"
        mode: 0400
    environment:
      - ADMIN_PASSWORD="/run/secrets/dfp_admin_password"
      - BACKUP=
    ports:
      - 38081:8081
    networks:
      - mainproxy
    deploy:
      replicas: 1 
      labels:
        - com.df.httpsOnly=true
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=nexus.outcome-hub.com
        - com.df.servicePath=/
        - com.df.port=8081
        - com.df.letsencrypt.host=nexus.outcome-hub.com
        - com.df.letsencrypt.email=email@outcome-hub.com
      placement:
        constraints:
          - "node.hostname == gerard"
#          - "node.role == worker"
networks:
  mainproxy:
    external: true
  
secrets:
  dfp_admin_password:
    external:
      name: "nexusadminpasswd"
